# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "218c4f7143e1533b03f408c80f4a010a"
name = "Fulfillzy"
handle = "Fulfillzy"
application_url = "https://9edd-103-182-161-55.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/orders-create"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_fulfillments,write_fulfillments"

[auth]
redirect_urls = [
  "https://39f7-103-182-161-55.ngrok-free.app/auth/callback",
  "https://39f7-103-182-161-55.ngrok-free.app/auth/shopify/callback",
  "https://39f7-103-182-161-55.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
